# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c1m2.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("#centralwidget{border-image: url(:/chapter1/resource/image/background.jpeg);}")
        self.centralwidget.setObjectName("centralwidget")
        self.combobox_serialport = QtWidgets.QComboBox(self.centralwidget)
        self.combobox_serialport.setGeometry(QtCore.QRect(80, 40, 69, 22))
        self.combobox_serialport.setObjectName("combobox_serialport")
        self.pushButton_serial = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_serial.setGeometry(QtCore.QRect(180, 40, 75, 23))
        self.pushButton_serial.setObjectName("pushButton_serial")
        self.textBrowser_log = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_log.setGeometry(QtCore.QRect(290, 80, 481, 271))
        self.textBrowser_log.setObjectName("textBrowser_log")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(300, 40, 71, 31))
        self.label.setObjectName("label")
        self.combobox_baudrate = QtWidgets.QComboBox(self.centralwidget)
        self.combobox_baudrate.setGeometry(QtCore.QRect(80, 80, 69, 22))
        self.combobox_baudrate.setObjectName("combobox_baudrate")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 50, 54, 12))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 90, 54, 12))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(290, 10, 151, 21))
        self.label_4.setObjectName("label_4")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_serial.setText(_translate("MainWindow", "打开串口"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p>记录日志</p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "串口号"))
        self.label_3.setText(_translate("MainWindow", "波特率"))
        self.label_4.setText(_translate("MainWindow", "智慧牧场网关系统"))
import myresource_rc
